### ISSUE TITLE
what kind of data are stored in file rel2candidates.json, e1rel_e2.json and path graph

### ISSUE THREAD

**Issue by lihuiliullh** [snap-stanford/csr#5]
May I know what kind of data are stored in file rel2candidates.json, e1rel_e2.json and path graph?
Can you share how you process the original triple data step by step?

**Comment by q-hwang** [comment]
Hi thanks for reaching out! I believe both files for NELL are taken from the MetaR repo and the original NELL-One dataset by Xiong et al. (https://arxiv.org/pdf/1808.09040.pdf). I generated them similarly for the other two datasets. 

I believe rel2candidates.json is supposed to contain all possible candidates for the tail node, and e1rel_e2.json is just adjacency list cached for easy access. For the two datasets I added, candidate set is simply all nodes.
